Sprints/1
microservices-course-itmo/crossroad-parser-service pull request #10
Opened 2020-09-27 18:11 UTC by Gollut

Finished the first Sprint

1. The main class structure was formed
2. Parsing Crossroads by pages, getting links for detailed pages, parsing detailed pages and building dto class
3. Basic tests

2020-09-27 21:50 UTC, shinehlina requested changes
Может не очень аккуратно посмотрела, но пока так) В общем классно, что вы завернули все это в Спринг)

Короче разберитесь там с помником, избавьтесь от лишнего.
Проверьте, что все запускается
Перенесите тесты в правильную папку и проверьте, что `mvn clean install` на стадии `test` их исполняет
Ну и там еще что написала)

2020-09-27 21:50 UTC, shinehlina commented on pom.xml
> +        </dependency>
Возьмите последний из помника

2020-09-27 21:50 UTC, shinehlina commented on pom.xml
> +            <artifactId>spring-boot-starter-test</artifactId>
Вот эта уже подключена выше

2020-09-27 21:50 UTC, shinehlina commented on pom.xml
> +            <version>4.12</version>
И эта уже содержится в spring-boot-starter-test, кажется

2020-09-27 21:50 UTC, shinehlina commented on pom.xml
> +            <artifactId>jackson-core</artifactId>
Jackson должны быть в spring web

2020-09-27 21:50 UTC, shinehlina commented on pom.xml
> +        </dependency>
И посмотрите на зависимости. На первый взгляд кажеься, что вы дублируете все, кроме jsoup. Уберите их и посмотрите, не сломается ли

2020-09-27 21:50 UTC, shinehlina commented on pom.xml
> +        </dependency>
И еще версию апните

2020-09-27 21:50 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad.parser/service/configuration/JobConfiguration.java
> +@PropertySource("classpath:application.properties")
Кажется, это можно не указывать, это путь по умолчанию

2020-09-27 21:50 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad.parser/service/configuration/JobConfiguration.java
> +@Import({ParserConfiguration.class})
Это зачем? Он не заавтовайрит без него?

2020-09-27 21:50 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad.parser/service/parse/requests/RequestsService.java
> +    //TODO kmosunoff переделать метод так, чтобы принимал
Это типа на следующий спринт?

2020-09-27 21:50 UTC, shinehlina commented on src/main/resources/application.properties
> +#Cron
Лучше напишите, как это читать) Типа "Каждые 12 часов" или что-то такое

2020-09-27 21:50 UTC, shinehlina commented on src/main/test/java/com/wine/to/up/crossroad/parser/service/job/ExportProductListJobTest.java
> +        export.runJob();
Эмммм... Я не поняла, что этот тест проверяет? Просто что такой бин есть? Возможно, это лишнее... 
Если нет, то напишите доку над ним

2020-09-27 21:50 UTC, shinehlina commented on src/main/test/java/com/wine/to/up/crossroad/parser/service/parse/requests/RequestsServiceTest.java
> +        log.debug(String.valueOf(pojo.get().getCount()));
Зачем debug в тестах? Лучше ассерт какой-то

2020-09-27 21:50 UTC, shinehlina commented on src/main/test/java/com/wine/to/up/crossroad/parser/service/db/constants/CurrencyTest.java
> +package com.wine.to.up.parser.service;
Кажется, что с пакетом что-то не так

2020-09-27 21:50 UTC, shinehlina commented on src/main/test/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseServiceTest.java
> +package com.wine.to.up.parser.service;
Здесь тоже пакет странно выглядит

2020-09-27 21:50 UTC, shinehlina commented on src/main/test/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseServiceTest.java
> +            = "src/main/test/java/com/wine/to/up/crossroad/parser/service/parse/service/catalog.html";
Где этот файл?

2020-09-27 21:50 UTC, shinehlina commented on src/main/test/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseServiceTest.java
> +            = "src/main/test/java/com/wine/to/up/crossroad/parser/service/parse/service/wine.html";
И этот тоже

2020-09-27 21:50 UTC, shinehlina commented on src/main/test/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseServiceTest.java
> +            = "src/main/test/java/com/wine/to/up/crossroad/parser/service/parse/service/wine.html";
И если у вас есть такие файлы, то лучше их положить в пакет resource в "test" (`src/test/resources`). В таком случае вам не придется описывать такой длинный путь. Возможно, найдете способ просто обратиться по имени

2020-09-27 21:50 UTC, shinehlina commented on src/main/test/java/com/wine/to/up/crossroad/parser/service/db/constants/CurrencyTest.java
> +import com.wine.to.up.crossroad.parser.service.db.constants.Currency;
Переместите папку "test" на уровень выше. Все тесты должны быть `src/test/java/com...`

2020-09-27 21:50 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad.parser/service/db/constants/Currency.java
> +    private static final Map<String, Currency> R = Arrays.stream(
R?

2020-09-27 21:50 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad.parser/service/job/ExportProductListJob.java
> +                int pages = (int) Math.ceil((double) pojo.get().getCount() / 30); // получить число страниц через RequestService
Этот коммент - это TODO?

2020-09-27 21:56 UTC, shinehlina commented
И еще лучше не называйте ветки со слешами. Только с `-`. При деплое могут проблемы потом возникнуть, так как Докер не любит специальные символы, а мы юзаем название ветки в названии имаджа

2020-09-28 06:05 UTC, Gollut commented on src/main/java/com/wine/to/up/crossroad.parser/service/job/ExportProductListJob.java
> +                int pages = (int) Math.ceil((double) pojo.get().getCount() / 30); // получить число страниц через RequestService
Нет, это описание строки

2020-09-28 12:29 UTC, shinehlina commented
> Возьмите последний из помника
Я имела ввиду из demo-service) Он с нашим парентом и без плагинов

2020-09-28 14:08 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/crossroad.parser/service/configuration/JobConfiguration.java
> +@Import({ParserConfiguration.class})
На сколько я понимаю, без этого импорта никак. 
Это решение нам понадобилось за тем, чтобы в случае добавления нового сайта для парсинга мы могли создать новый файл конфигурации парсера и подключать его к новому файлу джоба при этом переиспользуя старый класс RequestsService

2020-09-28 14:10 UTC, kmosunoff commented on src/main/java/com/wine/to/up/crossroad.parser/service/configuration/JobConfiguration.java
> +@PropertySource("classpath:application.properties")
Нужно указать

2020-09-28 14:11 UTC, kmosunoff commented on src/main/java/com/wine/to/up/crossroad.parser/service/configuration/JobConfiguration.java
> +@Import({ParserConfiguration.class})
Говорят, autowired - плохо...

2020-09-28 14:11 UTC, kmosunoff commented on src/main/resources/application.properties
> +#Cron
Fixed

2020-09-28 14:12 UTC, kmosunoff commented on src/main/test/java/com/wine/to/up/crossroad/parser/service/parse/requests/RequestsServiceTest.java
> +        log.debug(String.valueOf(pojo.get().getCount()));
fixed

2020-09-28 16:25 UTC, Anglopol requested changes

2020-09-28 16:25 UTC, Anglopol commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/serialization/ResponsePojo.java
> +public class ResponsePojo {
Не самое удачное имя класса

2020-09-28 16:25 UTC, Anglopol commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +    public static Optional<Product> parseProductPage(String html) {
Советую отказаться от использования статических методов и сделать данный сервис бином

2020-09-28 16:25 UTC, Anglopol commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +    private static final int BRAND = 1;
Лучше немного изменить название. Мне кажется, что название "BRAND_INDEX" (или подобное) более информативно, чем просто "BRAND"

2020-09-28 16:25 UTC, Anglopol commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +     * @return возвращает dto Product
Ваш метод возвращает Optional а не Product, лучше писать доку немного внимательнее

2020-09-28 16:25 UTC, Anglopol commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> + * @author 4ound
Странная документация класса, желательно присутствие какого-то описания, а не просто имени автора

2020-09-28 16:25 UTC, Anglopol commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +                    document
Странное форматирование

2020-09-28 16:25 UTC, Anglopol commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +            // страны нет
Зачем нужен этот комментарий в коде?

2020-09-28 17:04 UTC, Gollut commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/serialization/ResponsePojo.java
> +public class ResponsePojo {
Звучит субъективно

2020-09-28 17:07 UTC, Gollut commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> + * @author 4ound
Есть требования к описанию?

2020-09-28 17:07 UTC, Gollut commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +                    document
Есть требования к форматированию?

2020-09-28 17:12 UTC, 4ound commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +                    document
нормальное форматирование

2020-09-29 17:12 UTC, shinehlina requested changes

2020-09-29 17:12 UTC, shinehlina commented on pom.xml
Последний pom demo-service)

2020-10-04 11:43 UTC, Anglopol approved these changes

2020-10-04 11:58 UTC, shinehlina approved these changes

2020-10-04 14:12 UTC, merged