Sprint2
microservices-course-itmo/crossroad-parser-service pull request #25
Opened 2020-10-05 17:56 UTC by Gollut

2020-10-05 18:06 UTC, MaximKuznetsov17 commented on src/main/java/com/wine/to/up/crossroad/parser/service/configuration/KafkaConfiguration.java
> +        return new KafkaMessageSender<>(new KafkaProducer<>(producerProperties), "update-products" /*apiProperties.getTopicName()*/, new CommonMetricsCollector());
Не происходит инжект бина для ParserCommonApiProperties по умолчанию. Необходимо дописывать аннотацию Import и импортить класс компонента из common-parser-api. Но и при получении бина экземпляр не возвращает значение имени топика. Необходимо проверить правильность подключения пропертей в [parser-common-api](https://github.com/microservices-course-itmo/parser-common-api). Класс ParserCommonApiProperties

2020-10-06 10:57 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad/parser/service/configuration/KafkaConfiguration.java
> +        return new KafkaMessageSender<>(new KafkaProducer<>(producerProperties), "update-products" /*apiProperties.getTopicName()*/, new CommonMetricsCollector());
У меня есть сомнения в аннотации @ConfigurationProperties. Написала в pr. Но вообще мне не очень нравится, что нужны какие-то `@Import` аннотации, я постараюсь сегодня подумать еще)

2020-10-07 19:55 UTC, shinehlina requested changes
В целом лайк, минорные вещи

2020-10-07 19:55 UTC, shinehlina commented on pom.xml
> +        <parser.common.api.version>0.2.0-SNAPSHOT</parser.common.api.version>
Почему не 0.1.0? Лучше сделайте у этого коммон апи отсчет с 0.1.0

2020-10-07 19:55 UTC, shinehlina commented on pom.xml
>          <dockerfile-maven-plugin.version>1.4.13</dockerfile-maven-plugin.version>
Это похоже на лишнюю строчку

2020-10-07 19:55 UTC, shinehlina commented on pom.xml
>      </properties>
И версию самого приложения апните

2020-10-07 19:55 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad/parser/service/configuration/JobConfiguration.java
> +@Import({ParserConfiguration.class, KafkaConfiguration.class})
Кажется, выяснилось, что это лишнее

2020-10-07 19:55 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad/parser/service/configuration/KafkaConfiguration.java
> +@Import({ParserCommonApiProperties.class, CrossroadParserServiceMetricsCollector.class})
И вот этот тоже

2020-10-07 19:55 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +    private static final String SUGAR_NAME = "Сахaр";
Палец вверх за это

2020-10-07 19:55 UTC, shinehlina commented on src/test/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseServiceTest.java
> +    @Ignore
???

2020-10-07 20:50 UTC, MaximKuznetsov17 commented on src/test/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseServiceTest.java
> +    @Ignore
Многие наши тесты слишком долго прогоняются, чтобы каждый раз их запускать при сборке приложения. Поэтому лучше всего было пометить их этой аннотацией.

2020-10-11 20:13 UTC, shinehlina commented on src/test/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseServiceTest.java
> +    @Ignore
В след спринте лучше исправить. Продублирую здесь

> их надо оставить. Просто локально не исполнять. Все-таки мы бы хотели, чтобы при деплое максимально много можно было отловить. Там отдельно тесты не запускаются, только ваши. Те, что на  test стадии

2020-10-11 22:08 UTC, shinehlina approved these changes

2020-10-11 22:09 UTC, Anglopol approved these changes

2020-10-12 05:50 UTC, merged