Sprint5
microservices-course-itmo/crossroad-parser-service pull request #47
Opened 2020-10-26 12:06 UTC by Gollut

2020-10-31 13:04 UTC, shinehlina requested changes

2020-10-31 13:04 UTC, shinehlina commented on pom.xml
> +            <version>5.2</version>
Вынесите в проперти

2020-10-31 13:04 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +            return Optional.empty();
Если пустое описание, то не парсите продукт?

2020-10-31 13:04 UTC, shinehlina commented on src/test/java/com/wine/to/up/crossroad/parser/service/job/ExportProductListJobTest.java
> -            oldPrice += isNotZero(product.getOldPrice());
Убраоли?

2020-11-02 08:01 UTC, 4ound commented on src/test/java/com/wine/to/up/crossroad/parser/service/job/ExportProductListJobTest.java
> -            oldPrice += isNotZero(product.getOldPrice());
Да, сейчас, к сожалению, в перекрестке нет скидок ни на одно вино.
Так что хоть какой-то адекватный тест на oldPrice сделать не получится.

2020-11-04 16:36 UTC, shinehlina requested changes

2020-11-04 16:36 UTC, shinehlina commented on pom.xml
> +            <version>5.2.9.RELEASE</version>
Вы уверены, что без версий не работает? Если да, то вынесите в проперти

2020-11-04 16:36 UTC, shinehlina commented on src/test/java/com/wine/to/up/crossroad/parser/service/job/ExportProductListJobTest.java
> -            oldPrice += isNotZero(product.getOldPrice());
Но ведь если нет скидки,  то old и new price будут одинаковыми, нет?

2020-11-04 16:51 UTC, 4ound commented on src/test/java/com/wine/to/up/crossroad/parser/service/job/ExportProductListJobTest.java
> -            oldPrice += isNotZero(product.getOldPrice());
нет, если скидки нет, то мы сможем спарсить только одно поле цены
как только появляется скидка, на сайте отображается 2 поля - в этом случае мы их спарсим оба

не уверен, что с точки зрения парсинга в первом случае нужно заполнять оба поля одинаковыми значениями

2020-11-04 16:52 UTC, 4ound commented on pom.xml
> +            <version>5.2.9.RELEASE</version>
эти зависимости в итоге выпили в следующем спринте

2020-11-08 15:02 UTC, shinehlina commented on src/test/java/com/wine/to/up/crossroad/parser/service/job/ExportProductListJobTest.java
> -            oldPrice += isNotZero(product.getOldPrice());
Ну мне кажется, что лучше тогда одинаковыми, но ок, сейчас не критично

2020-11-08 15:03 UTC, shinehlina approved these changes

2020-11-08 17:02 UTC, merged