Sprint6
microservices-course-itmo/crossroad-parser-service pull request #55
Opened 2020-11-04 17:30 UTC by Gollut

2020-11-08 15:15 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad/parser/service/db/constants/Color.java
> +    private final String stringValue;
Может, name?

2020-11-08 15:26 UTC, shinehlina requested changes
Основное - это try с резурсами, я про long -> double не поняла. Про тесты - это скорее на будующее, можете потом попробовать

2020-11-08 15:26 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad/parser/service/job/ExportProductListJob.java
> +        double startTime = new Date().getTime();
Это как? Разве метод не long возвращает

2020-11-08 15:26 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/requests/RequestsService.java
> +            rd.close();
Давайте лучше try with resources

2020-11-08 15:26 UTC, shinehlina commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +                String capacity = value.replace(" л", "");
А у вас все объемы в литрах?

2020-11-08 15:26 UTC, shinehlina commented on src/test/java/com/wine/to/up/crossroad/parser/service/controller/ParseControllerTest.java
> +public class ParseControllerTest {
Вообще контроллеры можно не просто вызовом метода, запросами (mockMvc). Там можно и протестировать ExceptionHandler как работает

2020-11-08 17:03 UTC, Gollut commented on src/main/java/com/wine/to/up/crossroad/parser/service/parse/service/ParseService.java
> +                String capacity = value.replace(" л", "");
Да, все

2020-11-10 14:56 UTC, shinehlina approved these changes
Что это за файл?

2020-11-10 14:56 UTC, shinehlina commented on d
> +  'sprint4-fix-log[m
Это что за файл?

2020-11-14 15:32 UTC, merged